# ============================== Filebeat inputs ===============================
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.log
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: message

# ============================== Filebeat logging ===============================
# Manter esta secção para podermos ver a atividade do Filebeat
logging.level: info
logging.to_files: false
logging.to_stdout: true

# ================================== Outputs ===================================
# A secção de saída que estava em falta, a apontar para o Logstash
output.logstash:
  hosts: ["logstash:5044"]
