version: '3.8' 

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - app-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.0
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044" 
    # CORREÇÃO: Adiciona uma verificação de saúde para garantir que o Logstash está pronto
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - elasticsearch
    networks:
      - app-net

# SERVIÇO FILEBEAT
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.14.0
    container_name: filebeat
    command: -e -d "*" --strict.perms=false
    # ADIÇÃO: Permissão para o Filebeat acessar o Docker
    user: root 
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/usr/share/filebeat/logs
      # ADIÇÃO: Mapeia os logs dos contêineres Docker
      - /var/lib/docker/containers:/var/lib/docker/containers:ro 
      # ADIÇÃO: Mapeia o "soquete" do Docker para que o Filebeat possa obter metadados
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    depends_on:
      logstash:
        condition: service_healthy
    networks:
      - app-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_started
    networks:
      - app-net

volumes:
  mongo-data:
  es_data:
    driver: local

networks:
  app-net:
    driver: bridge
